[2024-07-26T23:33:06.598+0000] {processor.py:161} INFO - Started process (PID=1058) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:33:06.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:33:06.608+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:33:06.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:33:07.302+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:33:07.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:33:07.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:33:07.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.791 seconds
[2024-07-26T23:33:38.201+0000] {processor.py:161} INFO - Started process (PID=1068) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:33:38.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:33:38.217+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:33:38.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:33:38.953+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:33:38.946+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:33:38.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:33:38.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.809 seconds
[2024-07-26T23:34:09.875+0000] {processor.py:161} INFO - Started process (PID=1078) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:34:09.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:34:09.885+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:34:09.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:34:10.572+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:34:10.556+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:34:10.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:34:10.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.742 seconds
[2024-07-26T23:34:40.909+0000] {processor.py:161} INFO - Started process (PID=1088) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:34:40.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:34:40.912+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:34:40.912+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:34:41.476+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:34:41.472+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:34:41.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:34:41.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.589 seconds
[2024-07-26T23:35:11.813+0000] {processor.py:161} INFO - Started process (PID=1098) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:35:11.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:35:11.817+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:35:11.816+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:35:12.523+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:35:12.518+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:35:12.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:35:12.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.743 seconds
[2024-07-26T23:35:43.253+0000] {processor.py:161} INFO - Started process (PID=1108) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:35:43.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:35:43.259+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:35:43.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:35:43.797+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:35:43.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:35:43.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:35:43.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.570 seconds
[2024-07-26T23:36:14.093+0000] {processor.py:161} INFO - Started process (PID=1118) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:36:14.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:36:14.097+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:36:14.097+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:36:14.908+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:36:14.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:36:14.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:36:14.980+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.903 seconds
[2024-07-26T23:36:45.331+0000] {processor.py:161} INFO - Started process (PID=1128) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:36:45.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:36:45.336+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:36:45.335+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:36:46.086+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:36:46.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:36:46.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:36:46.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.797 seconds
[2024-07-26T23:37:16.391+0000] {processor.py:161} INFO - Started process (PID=1138) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:37:16.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:37:16.394+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:37:16.394+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:37:16.915+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:37:16.901+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:37:16.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:37:16.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.584 seconds
[2024-07-26T23:37:47.540+0000] {processor.py:161} INFO - Started process (PID=1148) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:37:47.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:37:47.549+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:37:47.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:37:48.014+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:37:48.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:37:48.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:37:48.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.515 seconds
[2024-07-26T23:38:18.671+0000] {processor.py:161} INFO - Started process (PID=1158) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:38:18.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:38:18.676+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:38:18.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:38:19.089+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:38:19.086+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:38:19.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:38:19.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.450 seconds
[2024-07-26T23:38:49.486+0000] {processor.py:161} INFO - Started process (PID=1168) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:38:49.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:38:49.489+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:38:49.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:38:50.003+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:38:49.991+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:38:50.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:38:50.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.556 seconds
[2024-07-26T23:39:20.370+0000] {processor.py:161} INFO - Started process (PID=1178) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:39:20.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:39:20.373+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:39:20.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:39:21.042+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:39:21.036+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:39:21.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:39:21.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.693 seconds
[2024-07-26T23:39:51.325+0000] {processor.py:161} INFO - Started process (PID=1188) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:39:51.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:39:51.329+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:39:51.329+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:39:52.018+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:39:51.986+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:39:52.044+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:39:52.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.843 seconds
[2024-07-26T23:40:22.665+0000] {processor.py:161} INFO - Started process (PID=1198) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:40:22.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:40:22.681+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:40:22.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:40:23.156+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:40:23.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:40:23.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:40:23.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.550 seconds
[2024-07-26T23:40:54.036+0000] {processor.py:161} INFO - Started process (PID=1207) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:40:54.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:40:54.044+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:40:54.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:40:54.688+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:40:54.684+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:40:54.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:40:54.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.707 seconds
[2024-07-26T23:41:24.858+0000] {processor.py:161} INFO - Started process (PID=1216) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:41:24.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:41:24.860+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:41:24.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:41:25.442+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:41:25.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:41:25.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:41:25.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.637 seconds
[2024-07-26T23:41:56.202+0000] {processor.py:161} INFO - Started process (PID=1226) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:41:56.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:41:56.209+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:41:56.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:41:56.969+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:41:56.954+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:41:56.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:41:57.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.834 seconds
[2024-07-26T23:42:28.039+0000] {processor.py:161} INFO - Started process (PID=1236) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:42:28.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:42:28.042+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:42:28.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:42:28.521+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:42:28.501+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:42:28.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:42:28.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.570 seconds
[2024-07-26T23:42:59.530+0000] {processor.py:161} INFO - Started process (PID=1246) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:42:59.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:42:59.531+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:42:59.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:42:59.936+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:42:59.925+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:42:59.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:42:59.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.437 seconds
[2024-07-26T23:43:30.719+0000] {processor.py:161} INFO - Started process (PID=1256) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:43:30.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:43:30.735+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:43:30.734+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:43:31.364+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:43:31.349+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:43:31.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:43:31.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.680 seconds
[2024-07-26T23:44:02.342+0000] {processor.py:161} INFO - Started process (PID=1266) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:44:02.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:44:02.358+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:44:02.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:44:02.883+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:44:02.879+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:44:02.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:44:02.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.575 seconds
[2024-07-26T23:44:33.360+0000] {processor.py:161} INFO - Started process (PID=1276) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:44:33.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:44:33.370+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:44:33.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:44:33.800+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:44:33.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:44:33.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:44:33.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.490 seconds
[2024-07-26T23:45:04.581+0000] {processor.py:161} INFO - Started process (PID=1286) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:45:04.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:45:04.583+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:45:04.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:45:05.179+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:45:05.172+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:45:05.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:45:05.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.653 seconds
[2024-07-26T23:45:35.757+0000] {processor.py:161} INFO - Started process (PID=1296) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:45:35.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:45:35.766+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:45:35.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:45:36.270+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:45:36.183+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:45:36.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:45:36.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.601 seconds
[2024-07-26T23:46:07.349+0000] {processor.py:161} INFO - Started process (PID=1312) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:46:07.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:46:07.352+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:46:07.352+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:46:07.779+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:46:07.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:46:07.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:46:07.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.487 seconds
[2024-07-26T23:46:38.823+0000] {processor.py:161} INFO - Started process (PID=1322) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:46:38.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:46:38.824+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:46:38.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:46:39.603+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:46:39.560+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:46:39.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:46:39.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.835 seconds
[2024-07-26T23:47:10.388+0000] {processor.py:161} INFO - Started process (PID=1332) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:47:10.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:47:10.395+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:47:10.394+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:47:10.880+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:47:10.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:47:10.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:47:10.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.523 seconds
[2024-07-26T23:47:41.125+0000] {processor.py:161} INFO - Started process (PID=1342) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:47:41.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:47:41.131+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:47:41.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:47:41.626+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:47:41.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:47:41.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:47:41.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.560 seconds
[2024-07-26T23:48:11.819+0000] {processor.py:161} INFO - Started process (PID=1351) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:48:11.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:48:11.821+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:48:11.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:48:12.256+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:48:12.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:48:12.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:48:12.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.470 seconds
[2024-07-26T23:48:42.532+0000] {processor.py:161} INFO - Started process (PID=1361) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:48:42.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:48:42.535+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:48:42.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:48:43.186+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:48:43.158+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:48:43.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:48:43.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.725 seconds
[2024-07-26T23:49:14.246+0000] {processor.py:161} INFO - Started process (PID=1371) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:49:14.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:49:14.253+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:49:14.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:49:14.843+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:49:14.812+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:49:14.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:49:14.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.689 seconds
[2024-07-26T23:49:45.133+0000] {processor.py:161} INFO - Started process (PID=1381) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:49:45.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:49:45.136+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:49:45.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:49:45.598+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:49:45.567+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:49:45.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:49:45.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.510 seconds
[2024-07-26T23:50:16.314+0000] {processor.py:161} INFO - Started process (PID=1391) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:50:16.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:50:16.318+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:50:16.316+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:50:16.948+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:50:16.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:50:16.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:50:16.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.662 seconds
[2024-07-26T23:50:47.248+0000] {processor.py:161} INFO - Started process (PID=1401) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:50:47.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:50:47.253+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:50:47.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:50:47.737+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:50:47.730+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:50:47.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:50:47.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.526 seconds
[2024-07-26T23:51:18.436+0000] {processor.py:161} INFO - Started process (PID=1411) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:51:18.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:51:18.441+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:51:18.441+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:51:19.139+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:51:19.127+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:51:19.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:51:19.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.759 seconds
[2024-07-26T23:51:49.353+0000] {processor.py:161} INFO - Started process (PID=1421) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:51:49.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:51:49.356+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:51:49.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:51:49.935+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:51:49.932+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:51:49.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:51:49.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.619 seconds
[2024-07-26T23:52:20.513+0000] {processor.py:161} INFO - Started process (PID=1431) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:52:20.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:52:20.516+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:52:20.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:52:21.117+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:52:21.105+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:52:21.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:52:21.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.639 seconds
[2024-07-26T23:52:52.034+0000] {processor.py:161} INFO - Started process (PID=1441) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:52:52.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:52:52.037+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:52:52.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:52:52.844+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:52:52.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:52:52.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:52:52.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.859 seconds
[2024-07-26T23:53:23.568+0000] {processor.py:161} INFO - Started process (PID=1451) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:53:23.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:53:23.576+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:53:23.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:53:24.116+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:53:24.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:53:24.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:53:24.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.579 seconds
[2024-07-26T23:53:54.256+0000] {processor.py:161} INFO - Started process (PID=1461) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:53:54.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:53:54.258+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:53:54.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:53:54.668+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:53:54.664+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:53:54.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:53:54.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.440 seconds
[2024-07-26T23:54:25.594+0000] {processor.py:161} INFO - Started process (PID=1471) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:54:25.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:54:25.601+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:54:25.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:54:26.034+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:54:26.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:54:26.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:54:26.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.468 seconds
[2024-07-26T23:54:56.509+0000] {processor.py:161} INFO - Started process (PID=1481) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:54:56.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:54:56.513+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:54:56.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:54:57.206+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:54:57.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:54:57.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:54:57.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.786 seconds
[2024-07-26T23:55:27.728+0000] {processor.py:161} INFO - Started process (PID=1491) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:55:27.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:55:27.745+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:55:27.744+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:55:28.399+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:55:28.393+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:55:28.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:55:28.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.742 seconds
[2024-07-26T23:55:58.656+0000] {processor.py:161} INFO - Started process (PID=1501) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:55:58.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:55:58.660+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:55:58.660+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:55:59.177+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:55:59.167+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:55:59.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:55:59.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.578 seconds
[2024-07-26T23:56:30.093+0000] {processor.py:161} INFO - Started process (PID=1511) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:56:30.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:56:30.108+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:56:30.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:56:30.725+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:56:30.713+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:56:30.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:56:30.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.685 seconds
[2024-07-26T23:57:00.858+0000] {processor.py:161} INFO - Started process (PID=1521) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:57:00.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:57:00.862+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:57:00.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:57:01.303+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:57:01.296+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:57:01.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:57:01.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.476 seconds
[2024-07-26T23:57:31.690+0000] {processor.py:161} INFO - Started process (PID=1531) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:57:31.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:57:31.694+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:57:31.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:57:32.182+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:57:32.179+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:57:32.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:57:32.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.513 seconds
[2024-07-26T23:58:02.851+0000] {processor.py:161} INFO - Started process (PID=1541) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:58:02.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:58:02.855+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:58:02.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:58:03.437+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:58:03.402+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:58:03.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:58:03.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.760 seconds
[2024-07-26T23:58:34.392+0000] {processor.py:161} INFO - Started process (PID=1551) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:58:34.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:58:34.395+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:58:34.394+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:58:34.826+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:58:34.820+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:58:34.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:58:34.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.464 seconds
[2024-07-26T23:59:05.369+0000] {processor.py:161} INFO - Started process (PID=1561) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:59:05.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:59:05.373+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:59:05.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:59:05.938+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:59:05.927+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:59:05.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:59:05.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.604 seconds
[2024-07-26T23:59:36.602+0000] {processor.py:161} INFO - Started process (PID=1571) to work on /opt/airflow/dags/funtions.py
[2024-07-26T23:59:36.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/funtions.py for tasks to queue
[2024-07-26T23:59:36.608+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:59:36.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/funtions.py
[2024-07-26T23:59:37.219+0000] {logging_mixin.py:188} INFO - [2024-07-26T23:59:37.205+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/funtions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/funtions.py", line 6, in <module>
    from ydata_profiling import ProfileReport
ModuleNotFoundError: No module named 'ydata_profiling'
[2024-07-26T23:59:37.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/funtions.py
[2024-07-26T23:59:37.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/funtions.py took 0.701 seconds
